from .basepruner import MetaPruner
from .magnitude_based_pruner import MagnitudePruner
from .batchnorm_scale_pruner import BNScalePruner
from .structural_reg_pruner import StructrualRegularizedPruner
from .structural_dropout_pruner import StructrualDropoutPruner
from .group_lasso_pruner import GroupLassoPruner